### POST Autor
POST http://127.0.0.1:8000/api/autors
Content-Type: application/json

{
    "nombre": "prueba",
    "apellido": "pruebaaa",
}

### GET Autores (index)
GET http://127.0.0.1:8000/api/autors
Content-Type: application/json
